from enum import Enum

import pygame


class GameEvents(Enum):
    SENT_LOGIN_REQUEST = pygame.USEREVENT + 1
    RECV_LOGIN_REQUEST_ACK = pygame.USEREVENT + 2
    SENT_AUTH_TOKEN = pygame.USEREVENT + 3
    RECV_AUTH_SUCCESSFUL = pygame.USEREVENT + 4
    SENT_KEEP_ALIVE = pygame.USEREVENT + 5
    SENT_UNKNOWN = pygame.USEREVENT + 6
    RECV_UNKNOWN = pygame.USEREVENT + 7
    SENT_END_GAME = pygame.USEREVENT + 8
    DISCONNECTED = pygame.USEREVENT + 9
    LOGIN_REQUEST_FAILED = pygame.USEREVENT + 10
    AUTH_FAILED = pygame.USEREVENT + 11
    RECV_SHUFFLE_SEED = pygame.USEREVENT + 12
    RECV_JOIN_TABLE = pygame.USEREVENT + 13
    RECV_PLAYER_DETAILS = pygame.USEREVENT + 14
    RECV_BEGIN_HAND = pygame.USEREVENT + 15
    RECV_RIICHI_DECLARED = pygame.USEREVENT + 16
    RECV_DORA_FLIPPED = pygame.USEREVENT + 17
    RECV_AGARI = pygame.USEREVENT + 18
    RECV_RYUUKYOKU = pygame.USEREVENT + 19
    RECV_CALL = pygame.USEREVENT + 20
    RECV_BEGIN_GAME = pygame.USEREVENT + 21
    RECV_DISCARD = pygame.USEREVENT + 22
    END_OF_GAME = pygame.USEREVENT + 23
    RECV_CALL_AVAILABLE = pygame.USEREVENT + 24
